---

- type: replace
  path: /releases/-
  value:
    name: syslog_to_loggregator
    version: latest

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: syslog_to_loggregator
    release: syslog_to_loggregator
    properties:
      syslog_to_loggregator:
        source_name: haproxy
        syslog_port: 1543
