---

- type: replace
  path: /releases/-
  value:
    name: syslog_to_loggregator
    version: latest

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: syslog_to_loggregator
    release: syslog_to_loggregator
    properties: {}
