groups: []
resources:
- name: git
  type: git
  source:
    branch: master
    ignore_paths:
    - releases/*
    private_key: {{git_private_key}}
    uri: git@github.com:govau/syslog-to-loggregator-boshrelease.git
- name: git-push
  type: git
  source:
    branch: master
    private_key: {{git_private_key}}
    uri: git@github.com:govau/syslog-to-loggregator-boshrelease.git
- name: github-release
  type: github-release
  source:
    access_token: {{git_personal_access_token}}
    owner: govau
    repository: syslog-to-loggregator-boshrelease
- name: version
  type: semver
  source:
    branch: master
    driver: git
    file: syslog-to-loggregator-boshrelease.version
    initial_version: 0.1.0
    private_key: {{git_boshreleases_private_key}}
    uri: git@github.com:govau/boshreleases.git
- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
resource_types:
- name: bosh2-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: v2.8.1
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.3.1
jobs:
- name: build-it
  plan:
  - aggregate:
    - get: version
      params:
        bump: minor
    - get: git
      trigger: true
  - task: create-bosh-release
    file: git/ci/create-bosh-release.yml
    params:
      access_key_id: {{boshrelease_s3_bucket_access_key_id}}
      bosh_release_name: syslog_to_loggregator
      secret_access_key: {{boshrelease_s3_bucket_secret_access_key}}
  - put: version
    params:
      file: version/version
  - put: git-push
    params:
      rebase: true
      repository: boshrelease-output
      tag: version/version
      tag_prefix: v
  - put: github-release
    params:
      body: github-release-info/body
      globs:
      - github-release-info/*-*.*.*.tgz
      name: github-release-info/name
      tag: github-release-info/tag
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :tada: $BUILD_PIPELINE_NAME created a new release of syslog-to-loggregator
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        $TEXT_FILE_CONTENT
      text_file: github-release-info/body
